config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#index'

  get 'reports', to: 'static_pages#reports'
  get 'analytics', to: 'static_pages#analytics'
  get 'news', to: 'static_pages#news'
  get 'articles/:id', to: 'static_pages#show_article', as: 'articles'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attack.rb
class Attack < ApplicationRecord
  default_scope { order('created_at DESC') }
  belongs_to :threat
end

app/models/threat.rb
class Threat < ApplicationRecord
  belongs_to :type
  has_many :attacks
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :threats
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
require 'csv'
require 'net/http'
require 'active_support/all'

class StaticPagesController < ApplicationController
  before_action :find_articles, only: [:news, :show_article]
  before_action :find_other_articles, only: [:news, :show_article]

  # def index
  #   @data = CSV.read("/home/bouzidi/Downloads/db123.csv")
  #   @columns = @data[0]
  #   @data.delete(@data[0])
  #   @rows = @data
  # end

  def index
    if params[:id]
      @attacks = Attack.where('id < ?', params[:id]).limit(5)
    else
      @attacks = Attack.limit(5)
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def reports
    if params[:id]
      @threats = Threat.where('id < ?', params[:id]).limit(5)
    else
      @threats = Threat.limit(15)
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def analytics
  end

  def news
  end

  def show_article
    if (params[:type] == 'article')
      @article = @items[params[:id].to_i]
    elsif (params[:type] == 'threatpost')
      @article = @threatposts[params[:id].to_i]
    end
  end

  private

    def find_articles
      @xml_content = Net::HTTP.get(URI.parse('http://extratorrent.cc/rss.xml?type=articles'))
      @data = Hash.from_xml(@xml_content)
      @items = @data["rss"]["channel"]["item"]
    end

    def find_other_articles
      @xml_content = Net::HTTP.get(URI.parse('https://threatpost.com/category/cloud-security/feed/'))
      @data = Hash.from_xml(@xml_content)
      @threatposts = @data["rss"]["channel"]["item"]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{ "type": "button", "data-toggle": "collapse", "data-target": "#navbar" }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Gestion de Threat", root_path, class: 'navbar-brand'
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-left
        %li= link_to 'Dashboard', root_path
        %li= link_to 'Reports', reports_path
        %li= link_to 'Analytics', analytics_path
        %li= link_to 'News', news_path

app/views/layouts/_sidebar.html.haml
%ul.nav.nav-sidebar
  %li.active= link_to 'Overview', root_path
  %li= link_to 'Reports', reports_path
  %li= link_to 'Analytics', analytics_path
  %li= link_to 'News', news_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Threats
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = render 'layouts/navigation'
    .container-fluid.content
      .row
        .col-sm-3.col-md-2.sidebar
          = render 'layouts/sidebar'
        .col-sm-9.col-md-10.main
          = yield

app/views/static_pages/analytics.html.haml
%h1.page-header Analytics
.row
  .col-md-8.col-md-offset-2
    %script{ "src": "https://securityalerts.mcafee.com/mcalerts/en-us/AlertConstant.js" }        
    %script{ "src": "https://securityalerts.mcafee.com/mcalerts/en-us/ResourceFile.js" }        
    %script{ "src": "https://securityalerts.mcafee.com/mcalerts/AlertDisplay.js" }
    %script
      DisplayMcAfeeAlerts();
                        

app/views/static_pages/index.html.haml
%h1.page-header Dashboard
.row
  .col-md-8
    .panel.panel-default
      .panel-heading Real-Time Attacks
      .panel-body
        .table-responsive
          %table.table
            %thead
              %tr
                %th Name
                %th Threat
                %th Attacker
                %th Attacker IP
                %th Attacker Geo
                %th Target
                %th Target IP
                %th Target Geo
            %tbody.attacks-container
              - @attacks.each do |attack|
                %tr{ class: "record", "data-id": attack.id }
                  %td= attack.name
                  %td= attack.threat.name
                  %td= attack.attacker
                  %td= attack.attacker_ip
                  %td= attack.attacker_geo
                  %td= attack.target
                  %td= attack.target_ip
                  %td= attack.target_geo
        .load-more-container
          = link_to "Load More", root_path, class: 'btn btn-default btn-sm load-more'
          = image_tag 'loading.gif', style: 'display: none', class: 'loading-gif'


  .col-md-4
    .panel.panel-default
      .panel-heading Main
      .panel-body
        %canvas#gauge

.row
  .col-md-4
    .panel.panel-default
      .panel-heading Gauges
      .panel-body
  .col-md-8
    .panel.panel-default
      .panel-heading Details
      .panel-body

app/views/static_pages/index.js.erb
<% if @attacks %>
  <% @attacks.each do |attack| %>
    $('.attacks-container').append(`
      <tr class='record' data-id='<%= attack.id %>'>
        <td><%= attack.name %></td>
        <td><%= attack.threat.name %></td>
        <td><%= attack.attacker %></td>
        <td><%= attack.attacker_ip %></td>
        <td><%= attack.attacker_geo %></td>
        <td><%= attack.target %></td>
        <td><%= attack.target_ip %></td>
        <td><%= attack.target_geo %></td>
      </tr>
    `);
  <% end %>
<% else %>
  $('.load-more').hide();
<% end %>

app/views/static_pages/index.new.html.haml
%h1.page-header Dashboard
.row
  .col-md-12
    .panel.panel-default
      .panel-heading Main
      .panel-body
        %canvas#gauge
        %canvas#gauge-low
        %canvas#gauge-medium
.row
  .col-md-12
    .panel.panel-default
      .panel-heading Real-Time Attacks
      .panel-body
        .table-responsive
          %table.table
            %thead
              - @columns.each do |column|
                %th= column
            %tbody.attacks-container
              - @rows.each do |row|
                %tr
                  - row.length.times do |index|
                    %td= row[index]

app/views/static_pages/news.html.haml
%h1.page-header Breaking News
.row
  .col-md-6
    %h4 Hacks
    %ul.list-group
      - @items.each_with_index do |item, index|
        %li.list-group-item
          %h3= link_to item["title"], articles_path(index, type: 'article')
  .col-md-6
    %h4 ThreatPost
    %ul.list-group
      - @threatposts.each_with_index do |item, index|
        %li.list-group-item
          %h3= link_to item["title"], articles_path(index, type: 'threatpost')

app/views/static_pages/reports.html.haml
%h1.page-header Reports
.row
  .col-md-12
    .panel.panel-default
      .panel-heading Risks
      .panel-body
        / %svg#pie{ "width": "960", "height": "500"}
.row
  .col-md-12
    .panel.panel-default
      .panel-heading Threat History
      .panel-body
        .table-responsive
          %table.table
            %thead
              %tr
                %th Name
                %th Description
                %th Risk
                %th Discovered
                %th Type
            %tbody.threats-container
            - @threats.each do |threat|
              %tr{ class: 'record', 'data-id': threat.id }
                %td= threat.name
                %td= threat.description
                %td= threat.risk
                %td= threat.date_discovered.strftime("%D")
                %td= threat.type.name
        .loading-animation
          = image_tag 'loading.gif', style: 'display: none', class: 'loading-gif'
          

app/views/static_pages/reports.js.erb
<% if @threats %>
  <% @threats.each do |threat| %>
    $('.threats-container').append(`
      <tr class="record" data-id="<%= threat.id %>">
        <td><%= threat.name %></td>
        <td><%= threat.description %></td>
        <td><%= threat.risk %></td>
        <td><%= threat.date_discovered.strftime('%D') %></td>
        <td><%= threat.type.name %></td>
      </tr>
    `);
  <% end %>
<% end %>

app/views/static_pages/show_article.html.haml
- if !@article.nil?
  %h1.page-header= @article["title"]
  %small{"style": "color: gray;"}= @article["pubDate"]
  .row
    .col-md-12
      %small= @article["description"]
      %hr/
      - if @article["encoded"]
        = @article["encoded"].html_safe
      - else
        = @article["description"].html_safe